# Generated by Django 4.2.26 on 2025-11-20 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('SERVICE', 'Beauty Service'), ('COURSE', 'Academy Course'), ('COMBO', 'Service Combo')], max_length=10)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('duration', models.PositiveIntegerField(help_text='Total duration in minutes')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('combo_services', models.ManyToManyField(blank=True, related_name='combo_bookings', to='services.service')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.course')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'ordering': ['-booking_date', '-booking_time'],
            },
        ),
    ]
